package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import interfaces.OnChangeScreen;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class CompeticaoController implements Initializable, OnChangeScreen {
	@FXML
	private Button bHistorico;
	@FXML
	private Button bResultados;
	@FXML
	private Button bJogadoresRegulares;
	@FXML
	private Button bAssistentes;
	@FXML
	private Button bArtilheiros;
	@FXML
	private Label lbJogadorRegular;
	@FXML
	private Label lbAssistente;
	@FXML
	private Label lbArtilheiro;

	// Event Listener on Button[#bHistorico].onAction
	@FXML
	public void historico(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bResultados].onAction
	@FXML
	public void verResultados(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bJogadoresRegulares].onAction
	@FXML
	public void jogadoresMaisRegulares(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bAssistentes].onAction
	@FXML
	public void verAssistentes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bArtilheiros].onAction
	@FXML
	public void verArtilheiros(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		Main.addOnChangeScreenListener(this);
		
	}
	@Override
	public void onScreenChanged(String newScreen, Object userData) {
		if(newScreen == "grupos"){
			this.lbArtilheiro.setText("Fernando Uribe");
			this.lbAssistente.setText("Paqueta");
			this.lbJogadorRegular.setText("Paqueta");
		}
		if(newScreen == "campeonato"){
			this.lbArtilheiro.setText("Vincius Jr");
			this.lbAssistente.setText("Benzema");
			this.lbJogadorRegular.setText("Vinicius Jr");
		}
		
	}
}
