package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import interfaces.OnChangeScreen;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class CopaController implements Initializable, OnChangeScreen {
	@FXML
	private ListView listaJogos;
	@FXML
	private Button bJogosAnteriores;
	@FXML
	private Button bJogosProx;

	// Event Listener on Button[#bJogosAnteriores].onAction
	@FXML
	public void jogosAnteriores(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bJogosProx].onAction
	@FXML
	public void jogosProx(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void onScreenChanged(String newScreen, Object userData) {
		
		
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		Main.addOnChangeScreenListener(this);
		
	}
}
