package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import interfaces.OnChangeScreen;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.image.ImageView;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class GerenciamentoDoTimeController implements Initializable, OnChangeScreen {
	@FXML
	private TableView tabela_jogadores;
	@FXML
	private TableColumn coluna_id;
	@FXML
	private TableColumn coluna_apelido;
	@FXML
	private TableColumn coluna_habilidade;
	@FXML
	private TableColumn coluna_enegia;
	@FXML
	private TableColumn coluna_gols;
	@FXML
	private TableColumn coluna_assists;
	@FXML
	private TableColumn coluna_forma;
	@FXML
	private TableColumn coluna_idade;
	@FXML
	private TableColumn coluna_satisfacao;
	@FXML
	private Button bEscalarTime;
	@FXML
	private ComboBox cbEscolherCapitao;
	@FXML
	private Label lbNumeroDeJogadores;
	@FXML
	private Label lbDinheiroEmCaixa;
	@FXML
	private Label lbJogadorChave;
	@FXML
	private Label lbArtilheiro;
	@FXML
	private Label lbGarcom;
	@FXML
	private Label lbMelhorForma;
	@FXML
	private Button bMensagens;
	@FXML
	private ImageView imgTimeAtual;

	// Event Listener on Button[#bEscalarTime].onAction
	@FXML
	public void escalacao(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bMensagens].onAction
	@FXML
	public void verMensagens(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void onScreenChanged(String newScreen, Object userData) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		Main.addOnChangeScreenListener(this);
	}
}
