package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import interfaces.OnChangeScreen;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.MenuItem;

import javafx.scene.control.Menu;

public class MenuFixoController implements Initializable, OnChangeScreen {
	@FXML
	private Button bVoltar;
	@FXML
	private Button bAvancar;
	@FXML
	private MenuItem miJogosClube;
	@FXML
	private MenuItem miJogosSelecao;
	@FXML
	private Menu menuCampeonatos;
	@FXML
	private Menu menuCopas;
	@FXML
	private Menu menuInternacionais;
	@FXML
	private Menu menuSelecoes;
	@FXML
	private MenuItem miClube;
	@FXML
	private MenuItem miJuniores;
	@FXML
	private MenuItem miSelecao;
	@FXML
	private Button bProcurar;
	@FXML
	private Button bFinancas;
	@FXML
	private Button bHistoria;
	@FXML
	private MenuItem miRankJogadores;
	@FXML
	private MenuItem miRankTecnicos;
	@FXML
	private MenuItem miRankClubes;
	@FXML
	private MenuItem miRankSelecoes;
	@FXML
	private Button bNoticias;
	@FXML
	private MenuItem miSalvar;
	@FXML
	private MenuItem miPreferencias;
	@FXML
	private MenuItem bSobre;
	@FXML
	private MenuItem miSair;
	@FXML
	private Button bAvancarTempo;

	// Event Listener on Button[#bVoltar].onAction
	@FXML
	public void telaAnterior(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bAvancar].onAction
	@FXML
	public void telaPosterior(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miJogosClube].onAction
	@FXML
	public void jogosClube(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miJogosSelecao].onAction
	@FXML
	public void jogosSelecao(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miClube].onAction
	@FXML
	public void verClube(ActionEvent event) {
		Main.changeScreen("gerenciamento");
	}
	// Event Listener on MenuItem[#miJuniores].onAction
	@FXML
	public void verJuniores(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miSelecao].onAction
	@FXML
	public void verAltualSelecao(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bProcurar].onAction
	@FXML
	public void procurarJogador(ActionEvent event) {
		Main.changeScreen("procurar");
	}
	// Event Listener on Button[#bFinancas].onAction
	@FXML
	public void verFinancas(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bHistoria].onAction
	@FXML
	public void historiaDoClube(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miRankJogadores].onAction
	@FXML
	public void rakingJogadores(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miRankTecnicos].onAction
	@FXML
	public void rakingTecnicos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miRankClubes].onAction
	@FXML
	public void rankingClubes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miRankSelecoes].onAction
	@FXML
	public void rankingSelecoes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bNoticias].onAction
	@FXML
	public void verNoticias(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miSalvar].onAction
	@FXML
	public void salvarJogo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miPreferencias].onAction
	@FXML
	public void verPreferencias(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#bSobre].onAction
	@FXML
	public void informacaoDoJogo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#miSair].onAction
	@FXML
	public void sairDoJogo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bAvancarTempo].onAction
	@FXML
	public void avancarTempo(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		Main.addOnChangeScreenListener(this);
		MenuItem itemCampeonato = new MenuItem("Brasileirão");
		MenuItem itemInternacional = new MenuItem("Libertadores");
		MenuItem itemCopa = new MenuItem("Copa do Brasil");
		menuCampeonatos.getItems().add(itemCampeonato);
		menuInternacionais.getItems().add(itemInternacional);
		menuCopas.getItems().add(itemCopa);
		itemCampeonato.setOnAction(new EventHandler<ActionEvent>(){

			@Override
			public void handle(ActionEvent event) {
				// TODO Auto-generated method stub
				System.out.println("ativou evento");
				Main.changeScreen("campeonato");
			}
			
		});
		itemInternacional.setOnAction(new EventHandler<ActionEvent>(){

			@Override
			public void handle(ActionEvent event) {
				// TODO Auto-generated method stub
				Main.changeScreen("grupos");
			}
			
		});
		itemCopa.setOnAction(new EventHandler<ActionEvent>(){

			@Override
			public void handle(ActionEvent event) {
				// TODO Auto-generated method stub
				Main.changeScreen("copa");
			}});
	}
	@Override
	public void onScreenChanged(String newScreen, Object userData) {
		// TODO Auto-generated method stub
		
	}
}
