package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import interfaces.OnChangeScreen;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ProcurarController implements Initializable, OnChangeScreen {
	@FXML
	private TextField tfPesquisa;
	@FXML
	private Button bPesquisar;
	@FXML
	private ComboBox cmbPosicao;
	@FXML
	private ComboBox cmbIdade;
	@FXML
	private ComboBox cmbCapacidade;
	@FXML
	private ComboBox cmbChute;
	@FXML
	private ComboBox cmbCabeceio;
	@FXML
	private ComboBox cmbCruzamentos;
	@FXML
	private ComboBox cmbPasse;
	@FXML
	private ComboBox cmbMarcacao;
	@FXML
	private ComboBox cmbPosicionamento;
	@FXML
	private ComboBox cmbTiroMeta;
	@FXML
	private ComboBox cmbForca;
	@FXML
	private ComboBox cmbDrible;
	@FXML
	private ComboBox cmbJogadaAerea;
	@FXML
	private ComboBox cmbDeterminacao;
	@FXML
	private ComboBox cmbRapidez;
	@FXML
	private ComboBox cmbDesarme;
	@FXML
	private ComboBox cmbReflexos;
	@FXML
	private ComboBox cmbResistencia;
	@FXML
	private ComboBox cmbNacionalidade;
	@FXML
	private ComboBox cmbLiga;
	@FXML
	private TableView tabelaJogadores;
	@FXML
	private TableColumn coluna_id;
	@FXML
	private TableColumn coluna_nome;
	@FXML
	private TableColumn coluna_idade;
	@FXML
	private TableColumn coluna_capacidade;
	@FXML
	private TableColumn coluna_nacionalidade;
	@FXML
	private TableColumn coluna_liga;
	@FXML
	private TableColumn coluna_clube;
	@FXML
	private TableColumn coluna_gols;
	@FXML
	private TableColumn coluna_assists;
	@FXML
	private TableColumn coluna_classMedia;
	@FXML
	private TableColumn coluna_valorMercado;
	@FXML
	private TableColumn coluna_disp;
	@FXML
	private ComboBox cmbDisponibilidade;
	@FXML
	private ComboBox cmbValor;
	@FXML
	private ComboBox cmbSatisfacao;

	// Event Listener on Button[#bPesquisar].onAction
	@FXML
	public void pesquisarJogador(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void onScreenChanged(String newScreen, Object userData) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		Main.addOnChangeScreenListener(this);
		
	}
}
