package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import interfaces.OnChangeScreen;
import javafx.event.ActionEvent;

public class TelaInicialController implements Initializable, OnChangeScreen {
	@FXML
	private Button bNovoJogo;
	@FXML
	private Button bCarregarJogo;
	@FXML
	private Button bEditar;

	// Event Listener on Button[#bNovoJogo].onAction
	@FXML
	public void novoJogo(ActionEvent event) {
		Main.changeScreen("menu");
	}
	// Event Listener on Button[#bCarregarJogo].onAction
	@FXML
	public void carregarJogo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bEditar].onAction
	@FXML
	public void editar(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void onScreenChanged(String newScreen, Object userData) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		Main.addOnChangeScreenListener(this);
		
	}
}
